import type { Metadata } from "next";
import {
  ClerkProvider,
  // SignInButton,
  // SignedIn,
  // UserButton,
} from "@clerk/nextjs";
import "./globals.css";
import { raleway, poppins } from "./fonts/fonts";

export const metadata: Metadata = {
  title: "pichaHub | Discover, Organize, and Share Your Memories.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${raleway.variable} ${poppins.variable} antialiased`}
      >
        <body className={`${poppins.className}`}> {children}</body>
      </html>
    </ClerkProvider>
  );
}
