import type { Metadata } from "next";
import "./globals.css";
import { raleway, poppins } from "./fonts/fonts";

import Layout from "@/Layout";

export const metadata: Metadata = {
  title: "pichaHub | Discover, Organize, and Share Your Memories.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${raleway.variable} ${poppins.variable} antialiased`}
    >
      <body className={`${poppins.className}`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
